vich_uploader:
    db_driver: orm

    mappings:
       vehicules_image:
           uri_prefix: /images/vehicules
           upload_destination: '%kernel.project_dir%/public/images/vehicules'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
